# Generated by Django 5.0 on 2023-12-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("moderators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="practice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="moderators.practice",
                verbose_name="Выбранная практика",
            ),
        ),
    ]
