# Generated by Django 5.0 on 2023-12-27 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="position",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Регион присутствия",
                "verbose_name_plural": "Регионы присутствия",
            },
        ),
        migrations.CreateModel(
            name="speciality",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальности",
            },
        ),
        migrations.CreateModel(
            name="representatives_staff",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "second_name",
                    models.CharField(max_length=150, verbose_name="Фамилия"),
                ),
                (
                    "middle_name",
                    models.CharField(max_length=150, verbose_name="Отчество"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=17, verbose_name="Номер телефона"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.position",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.speciality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Представитель СУЗ/ВУЗ",
                "verbose_name_plural": "Представители СУЗ/ВУЗ",
            },
        ),
    ]
