# Generated by Django 5.0 on 2023-12-27 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Moderator_base",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "second_name",
                    models.CharField(max_length=255, verbose_name="Фамилия"),
                ),
                (
                    "middle_name",
                    models.CharField(max_length=255, verbose_name="Отчество"),
                ),
                (
                    "subdivision",
                    models.CharField(
                        default=" ",
                        max_length=255,
                        verbose_name="Название подразделения",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=17, verbose_name="Номер телефона"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                (
                    "post",
                    models.CharField(
                        default=" ", max_length=255, verbose_name="Должность"
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.position",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Модератор",
                "verbose_name_plural": "Модераторы",
            },
        ),
        migrations.DeleteModel(
            name="representatives_staff",
        ),
    ]
