# Generated by Django 5.0 on 2023-12-27 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_moderator_base_delete_representatives_staff"),
        ("moderators", "0002_alter_practice_region_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="position",
            new_name="Regions",
        ),
        migrations.RenameField(
            model_name="moderator_base",
            old_name="position",
            new_name="region",
        ),
    ]
