# Generated by Django 5.0 on 2023-12-27 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_moderator_base_delete_representatives_staff"),
        ("moderators", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practice",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.position",
                verbose_name="Регион",
            ),
        ),
        migrations.AlterModelOptions(
            name="trainingdirections",
            options={
                "verbose_name": "Направление практики",
                "verbose_name_plural": "Направления практики",
            },
        ),
        migrations.DeleteModel(
            name="Moderator",
        ),
        migrations.DeleteModel(
            name="REGIONS",
        ),
    ]
